resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.
    all:
      vars:
        ansible_connection: ssh
        ansible_user: centos
    elasticsearch:
      hosts:
        node01.netology.yc: 
          ansible_host: ${yandex_compute_instance.node01.network_interface.0.nat_ip_address}
    kibana:
      hosts:
        node02.netology.yc:
          ansible_host: ${yandex_compute_instance.node02.network_interface.0.nat_ip_address}
    filebeat:
      hosts:
        node03.netology.yc: 
          ansible_host: ${yandex_compute_instance.node03.network_interface.0.nat_ip_address}       
    DOC
    
  filename = "../inventory/prod/hosts.yml"

  depends_on = [
    yandex_compute_instance.node01,
    yandex_compute_instance.node02,
    yandex_compute_instance.node03
  ]
}